.TH XHIDECURSOR 1 "" "xhidecursor" "User Commands"
.SH NAME
xhidecursor \- hide the mouse cursor when typing
.SH SYNOPSIS
.B xhidecursor
.SH DESCRIPTION
.B xhidecursor
hides the mouse cursor when a key is pressed and shows it again when the mouse
is moved. Modifier keys are ignored.
.SH REQUIREMENTS
XInput2 version 2.0 or later and the XFixes extension are required.
.SH AUTHOR
Written by Aleksandrs Stier <aleks.stier@icloud.com>.
